
#server:
#  port: 7200
#  servlet:
#    session:
#      timeout: 30m
#
#spring:
#  application:
#    name: gulimall-product
#  datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.111.154:3306/gulimail_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#      username: root
#      password: root
#
#
#
##  cloud:
##    nacos:
##      discovery:
##        server-addr: localhost:8848
##
##    sentinel:
##      transport:
##        #配置sentinel dashboard地址
##        dashboard: localhost:8080
##
##  redis:
##    host: 192.168.77.130
##    port: 6379
#
##开启feign对sentinel的支持
##feign:
##  sentinel:
##    enabled: true
##
##  jackson:
##    date-format: yyyy-MM-dd HH:mm:ss
##
##    #关闭thymeleaf缓存
##  thymeleaf:
##    cache: false
##
##  session:
##    store-type: redis
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#
#  #设置实体类的自增主键
#  global-config:
#    db-config:
#      id-type: auto
#      #逻辑删除
#      logic-delete-value: 1
#      logic-not-delete-value: 0
##
##logging:
##  level:
##    com.xunqi.gulimall: error
#
#
###暴露所有端点
##management:
##  endpoints:
##    web:
##      exposure:
##        include: '*'