spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-admin
          predicates:
              - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-admin/$\{segment}

        - id: gulimail_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimail_auth_route
          uri: lb://gulimail-auth-server
          predicates:
            - Host=auth.gulimall.com

        - id: gulimail_search_route
          uri: lb://gulimail-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimail_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimail_order_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimail_member_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com

        - id: gulimail_coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Host=coupon.gulimall.com

#        - id: gulimall_seckill_route
#          uri: lb://gulimall-seckill
#          predicates:
#            - Host=seckill.gulimall.com
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#              - Query=url,qq
#暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'